### ISSUE TITLE
You could use buildin `rotr` and `rotl` intrinsics instead emulated it via xor shifts

### ISSUE THREAD

**Issue by MaxGraey** [GuildOfWeavers/merkle#3]
See https://docs.assemblyscript.org/basics/environment#math

**Comment by bobbinth** [comment]
thanks! I've just pushed a commit which includes this change. btw, in my high-level testing, the WASM version of Blake2s is almost 2x faster than Node's native version.

**Comment by MaxGraey** [comment]
nice!

**Comment by bobbinth** [comment]
I think with SIMD it could be another 2x - 3x faster, but it seems SIMD is still kind of buggy with WASM/AssemblyScript.
